### ISSUE TITLE
Block-scoped declarations

### ISSUE THREAD

**Issue by yozawiratama** [andmev/stegjs#1]
```
C:\Users\Y50\AppData\Roaming\npm\node_modules\stegjs\bin\stegjs:32
let imageValue;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by andmev** [comment]
Thanks for your feedback! I will close the issue.
